// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PiASP {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm sendmessage;
		
		protected System.Web.UI.WebControls.TextBox MessageText;
		
		protected System.Web.UI.WebControls.Label MessageResponse;
		
		protected System.Web.UI.WebControls.Button MessageSend;
	}
}
